### ISSUE TITLE
add `postgresql` to `sztp`

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-poc#104]
like
```
volumes:
  sztp_data: {}

services:
  db:
    image: postgres:9.5
    volumes:
      - sztp_data:/var/lib/postgresql/data
```
