### ISSUE TITLE
add healthcheck to spdk dockerfile

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-poc#144]
in https://github.com/opiproject/opi-poc/blob/main/storage/Dockerfile

```
HEALTHCHECK CMD curl --fail --insecure --user spdkuser:spdkpass -X POST -H 'Content-Type: application/json' -d '{\"id\": 1, \"method\": \"bdev_get_bdevs\"}' http://localhost:9009 || exit 1
```
in addition to what we have in compose
```
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --insecure --user spdkuser:spdkpass -X POST -H 'Content-Type: application/json' -d '{\"id\": 1, \"method\": \"bdev_get_bdevs\"}' http://localhost:9009 || exit 1"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s
```
check via
```
 $ docker inspect --format='{{json .State.Health.Status}}' opi-spdk | jq
"healthy"
```
